### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by xenoterracide** [connor4312/cockatiel#62]
I'm not sure how to reproduce this but reading `abort.ts` it's calling new, but no import of the class is ever done. using 3 beta.1 I have to be honest, I have no idea how this even compiles https://github.com/connor4312/cockatiel/blob/7525ad893c705f4c34895839993f19c718f2673a/src/common/abort.ts

```
[2022-06-08T19:20:38.022Z]        2022-06-08T19:19:29.101Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"AbortController is not defined","stack":["ReferenceError: AbortController is not defined","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/common/abort.js:5:34)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Module.require (internal/modules/cjs/loader.js:887:19)","    at require (internal/modules/cjs/helpers.js:74:18)","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/CircuitBreakerPolicy.js:4:17)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Module.require (internal/modules/cjs/loader.js:887:19)","    at require (internal/modules/cjs/helpers.js:74:18)","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/breaker/SamplingBreaker.js:4:32)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Module.require (internal/modules/cjs/loader.js:887:19)","    at require (internal/modules/cjs/helpers.js:74:18)","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/breaker/Breaker.js:17:14)"]}
```

**Comment by connor4312** [comment]
3.0.0 [requires Node 16 or higher](https://github.com/connor4312/cockatiel/blob/7525ad893c705f4c34895839993f19c718f2673a/package.json#L8) where the `AbortController` is available. Or you could add a global polyfill for it.

**Comment by xenoterracide** [comment]
Oh, So that's a node type? Maybe add an import from node for readability...

 Either way that explains why I didn't see it locally. Locally I'm running node 16.

Also, does the package.json provide the requirement of greater than node 16? You can do that, And probably should.

**Comment by connor4312** [comment]
It's in both Node and the browsers. This is the compatibility chart for it: https://developer.mozilla.org/en-US/docs/Web/API/AbortController#browser_compatibility
